#!/bin/bash

declare -A addresses=(
	["site1"]="http://localhost:3000"
	["site2"]="http://localhost:4000"
	["site3"]="http://localhost:5000"
	["site4"]="http://localhost:6000"
)

site="site1"

echo -n "DB: "
curl -w "\n" "${addresses[$site]}/db"
echo

curl -w "\n" -H "Content-Type: application/json" --data "@$1" "${addresses[$site]}/coordinator/transact"

echo
echo -n "DB: "
curl -w "\n" "${addresses[$site]}/db"
