#!/bin/bash

declare -A addresses=(
	["site1"]="http://localhost:3000"
	["site2"]="http://localhost:4000"
	["site3"]="http://localhost:5000"
	["site4"]="http://localhost:6000"
)

print_db(){
	echo -e "\nDB:"
	echo -ne "a = " && curl -w "\n" "${addresses["site1"]}/db/a"
	echo -ne "b = " && curl -w "\n" "${addresses["site2"]}/db/b"
	echo -ne "c = " && curl -w "\n" "${addresses["site3"]}/db/c"
	echo -ne "d = " && curl -w "\n" "${addresses["site4"]}/db/d"
}

site="site1"

print_db

echo -e "\nPerforming transaction"
curl -w "\n" -H "Content-Type: application/json" --data "@$1" "${addresses[$site]}/coordinator/transact"

print_db
